export const permissions = [
  "BUSINESS_VIEW",
  "BUSINESS_UPDATE",

  "BRANCH_VIEW",
  "BRANCH_CREATE",
  "BRANCH_UPDATE",
  "BRANCH_ASSIGN_STAFF",

  "STAFF_VIEW",
  "STAFF_CREATE",
  "STAFF_UPDATE",
  "STAFF_DISABLE",
  "STAFF_ASSIGN_BRANCH",
  "STAFF_REMOVE_FROM_BRANCH",
  "STAFF_ASSIGN_ROLE",
  "STAFF_REMOVE_ROLE",
  "STAFF_RESET_PASSWORD",

  "OWNER_CREATE",
  "OWNER_REMOVE",
  "PARTNER_CREATE",
  "PARTNER_UPDATE",
  "PARTNER_REMOVE",

  "ORDER_CREATE",
  "ORDER_SUBMIT",
  "ORDER_VIEW",
  "ORDER_CANCEL_REQUEST",

  "PAYMENT_COLLECT",
  "PAYMENT_VIEW",
  "PAYMENT_REFUND_REQUEST",

  "STOCK_VIEW",
  "STOCK_RESERVE",
  "STOCK_RELEASE",
  "STOCK_ADJUSTMENT_REQUEST",

  "SERVICE_VIEW",
  "SERVICE_COMPLETE",

  "EXPENSE_VIEW",
  "EXPENSE_CREATE",
  "EXPENSE_APPROVE",

  "SUPPLIER_VIEW",
  "SUPPLIER_BILL_CREATE",
  "SUPPLIER_PAYMENT_REQUEST",
  "SUPPLIER_PAYMENT_APPROVE",

  "CASH_SESSION_OPEN",
  "CASH_SESSION_CLOSE",
  "CASH_SESSION_VIEW",

  "REPORT_VIEW",
  "RISK_VIEW",
  "APPROVAL_DECIDE",
  "ACTIVITY_VIEW",

  "OFFLINE_SYNC_SUBMIT",
] as const;

export type Permission = (typeof permissions)[number];
